config/routes.rb
Rails.application.routes.draw do
  get '/auth/amazon/callback' => 'sessions#create'
  get 'shows/search' => 'shows#search'
  post 'shows/result' => 'shows#results'
  resources :shows do
    resources :comments
  end
  resources :watchlists
  resources :users, only: [:show, :new, :create, :edit, :update]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'users#welcome'
  get 'users/welcome' => 'users#welcome'
  get 'sessions/sign_in' => 'sessions#new'
  post 'sessions/create' => 'sessions#create'
  get "sessions/destroy" => 'sessions#destroy'


end

app/models/watchlist.rb
class Watchlist < ApplicationRecord
  belongs_to :user
  has_many :shows, dependent: :delete_all
  validates :title, presence: true
end

app/controllers/watchlists_controller.rb
class WatchlistsController < ApplicationController
  before_action :set_watchlist, only: [:show, :edit, :update, :destroy]
  def new
    @watchlist = Watchlist.new
    @user = current_user
  end

  def create
    @user = current_user
    @watchlist = @user.watchlists.create(watchlist_params)
    if @watchlist.save
      redirect_to watchlist_path(@watchlist.id), notice: 'Watchlist created.'
    else
      render new_watchlist_path
    end
  end

  def edit
    # helper to check if current user can edit this watchlist
    unless access_permitted?
      redirect_to root_path, notice: 'Access denied.'
    end
  end

  def update
    # helper to check if current user can update this watchlist
    unless access_permitted?
      redirect_to root_path, notice: 'Access denied.'
    else
      @watchlist.update(watchlist_params)
      redirect_to root_path, notice: 'Watchlist successfully updated.'
    end
  end

  def show
    # helper to check if current user can view this watchlist
    unless access_permitted?
      redirect_to root_path, notice: 'Access denied.'
    else
      @shows = @watchlist.shows
    end
  end

  def index
    @user = current_user
    @watchlists = @user.watchlists
  end

  def destroy
    # helper to check if current user can delete this watchlist
    unless access_permitted?
      redirect_to root_path, notice: 'Access denied.'
    else
      @watchlist.destroy
      redirect_to root_path, notice: 'Watch list deleted.'
    end
  end

  private

  def set_watchlist
    @watchlist = Watchlist.find_by(:id => params[:id])
  end

  def watchlist_params
    params.require(:watchlist).permit(:title, :user_id)
  end

end

app/helpers/watchlists_helper.rb
module WatchlistsHelper
end

app/views/watchlists/_form.html.erb
<% if @watchlist.errors.any? %>
  <%= error_helper(@watchlist) %>
  <%= error_list(@watchlist) %>
<% end %>



<%= form_for @watchlist do |f| %>
<div><%= f.label :title %></div>
<div><%= f.text_field :title %></div><br>
<div><%= f.submit %></div>
<% end %>

app/views/watchlists/_watchlist.html.erb
<ul>
    <li><%= link_to  watchlist.title, watchlist_path(watchlist) %></li>
</ul>

app/views/watchlists/index.html.erb
<ul>
<% @watchlists.each do |w| %>
  <li><%= link_to w.title, watchlist_path(w) %></li>
  <% end %>
</ul>
<%= link_to "Create New Watchlist", new_watchlist_path %>

app/views/watchlists/show.html.erb
<h3>Watchlist: <%= link_to @watchlist.title, edit_watchlist_path(@watchlist) %></h3>
<%= button_to "delete", @watchlist, :method => :delete %>

<table>
  <tr>
    <th>Show </th>
    <th>Genre </th>
    <th>Type </th>
  </tr>

    <%= render @shows %><br>

</table>

<p><%= link_to 'Add New Show', new_show_path %></p>
<button data-list="<%=@watchlist.id%>" onclick="sortShows(event)">Sort</button>

<div><ul id="watchlistSort"></ul></div>