config/routes.rb
Rails.application.routes.draw do
  get '/auth/amazon/callback' => 'sessions#create'
  get 'shows/search' => 'shows#search'
  post 'shows/result' => 'shows#results'
  resources :shows do
    resources :comments
  end
  resources :watchlists
  resources :users, only: [:show, :new, :create, :edit, :update]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'users#welcome'
  get 'users/welcome' => 'users#welcome'
  get 'sessions/sign_in' => 'sessions#new'
  post 'sessions/create' => 'sessions#create'
  get "sessions/destroy" => 'sessions#destroy'


end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :show
  validates :title, presence: true
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
skip_before_action :require_login
  def new
    @show = Show.find_by(:id => params[:show_id])
    @comment = Comment.new

  end

    def create

      @show = Show.find_by(:id => params[:show_id])
      @comment = @show.comments.build(comment_params[:comment])
      @comment.save
      @comments = @show.comments # I didn't do this
        respond_to do |format|
          format.html {render "/comments/index"}
          format.json {render json: @comments} #.to_json(only: [:title, :body, :id])}
        end
    end

  def edit
    #use the access_permitted helper to determine if the current user can edit this comment
    unless access_permitted?
      redirect_to root_path, notice: 'Access denied'
    else
      @comment = Comment.find_by(:id => params[:id])
      @show = Show.find_by(:id => params[:show_id])
    end
  end

  def update
    #use the access_permitted helper to determine if the current user can edit this comment
    unless access_permitted?
      redirect_to root_path, notice: 'Access denied'
    else
      @show = Show.find_by(:id => params[:show_id])
      @comment = Comment.find_by(:id => params[:id])
      @comment.update(comment_params[:comment])
      if @comment.save
        redirect_to show_path(@comment.show_id)
      else
        render show_comments_path
      end
    end

  end

  def show
    #use the access_permitted helper to determine if the current user can edit this comment
    unless access_permitted?
      redirect_to root_path, notice: 'Access denied'
    else

      @show = Show.find_by(:id => params[:show_id])
      @comment = Comment.find_by(:id => params[:id])

        respond_to do |format|
          format.html {render "/comments/show"}
          format.json {render json: @comment} #.to_json(only: [:title, :body, :id])}
        end

    end
  end

  def index
    if logged_in?
      @show = Show.find_by(:id => params[:show_id])
      @comments = @show.comments

      respond_to do |format|
        format.html {render "/comments/index"}
        format.json {render json: @comments} #.to_json(only: [:title, :body, :id])}
      end
    end
  end

  private
  def set_comment
    @comment = Comment.find_by(:id => params[:id])
  end

  def comment_params
    params.permit(:show_id, comment: [:title, :body])
  end

end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_form.html.erb
<% if @comment.errors.any? %>
  <%= error_helper(@comment) %>
  <%= error_list(@comment) %>
<% end %>

<%= form_for [@show, @comment] do |f| %>
  <%= f.label 'Comment Title' %>
  <%= f.text_field :title %><br><br>
  <%= f.label 'Comment' %>
  <%= f.text_area :body %><br><br>
  <%= f.submit %>
<% end%>

app/views/comments/_index.html.erb
<ul>
<% @comments.each do |c| %>
  <li><%= link_to c.title,  show_comment_path(@show, c)%></li>
  <% end %>
</ul>

app/views/comments/edit.html.erb
<%= render 'form' %>

app/views/comments/form.html.erb
<% if @comment.errors.any? %>
  <%= error_helper(@comment) %>
  <%= error_list(@comment) %>
<% end %>
<%= form_tag show_comments_path(@show) do |f| %>
<%= label_tag 'title' %>
<%= text_field_tag :title %><br><br>
<%= text_area_tag 'body', nil, size: '50x5' %>
<%= submit_tag %>
<% end %>

app/views/comments/index.html.erb
<%= render 'index' %>

app/views/comments/new.html.erb
<%= render 'form' %>

app/views/comments/show.html.erb
<div>
<h3 id="comment_title"><%= @comment.title %></h3>

<p id="comment_body"><%= @comment.body %></p>
<%= link_to "edit", edit_show_comment_path(@comment.show_id, @comment) %><br>
<button id="next_comment", data-comment="<%=@comment.id%>" data-show="<%=@comment.show_id%>" onclick="nextComment()">Next</button>
<button class="add_comment", data-comment="<%=@comment.id%>", data-show="<%=@show.id%>" onclick="addCommentForm()">Add Comment</button>
</div><br>
<div class="form_div" class="flex-container"></div>