config/routes.rb
Rails.application.routes.draw do
  get '/auth/amazon/callback' => 'sessions#create'
  get 'shows/search' => 'shows#search'
  post 'shows/result' => 'shows#results'
  resources :shows do
    resources :comments
  end
  resources :watchlists
  resources :users, only: [:show, :new, :create, :edit, :update]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'users#welcome'
  get 'users/welcome' => 'users#welcome'
  get 'sessions/sign_in' => 'sessions#new'
  post 'sessions/create' => 'sessions#create'
  get "sessions/destroy" => 'sessions#destroy'


end

app/models/user.rb
class User < ApplicationRecord
  has_many :watchlists
  has_many :shows, through: :watchlists
  has_many :comments, through: :shows

  has_secure_password
  validates :name, presence: true, uniqueness: true
  validates :email, presence: true, email: true

  def self.find_or_create_by_omniauth(auth)

    @user = User.find_or_create_by(uid: auth['uid']) do |u|
      u.name = auth['info']['name']
      u.email = auth['info']['email']
      u.password = SecureRandom.hex
      u.save
    end

  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update]
  skip_before_action :require_login, only: [:welcome, :new, :create]
  def welcome
    if logged_in?
      @watchlists = current_user.watchlists
    end
  end

  def show
  end

  def new
    @user = User.new
  end

  def create
    if  params[:user][:password] == params[:user][:password_confirmation]
      @user = User.create(user_params)
    end
      if @user.save
        session[:user_id] = @user.id
        render '/users/welcome'
      else
        render '/users/new'
      end
  end

  def edit
    unless access_permitted?
      redirect_to root_path, notice: 'Access denied'
    end
  end

  def update
    unless access_permitted?
      redirect_to root_path, notice: 'Access denied'
    else
      if @user.update(user_params)
        redirect_to user_path(@user), notice: 'User updated.'
      else
        render :edit
      end
    end
  end




  private

  def set_user
    @user = User.find_by(:id => params[:id])
  end

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<% if @user.errors.any? %>
    <%= error_helper(@user) %>
    <%= error_list(@user) %>
<% end %>

<%= form_for(@user) do |f| %>
Name: <%= f.text_field :name %><br><br>
Email: <%= f.text_field :email %><br><br>
Password: <%= f.password_field :password %><br><br>
Password Confirmation: <%= f.password_field :password_confirmation %>
<%= f.submit "Submit" %>
<% end %>

app/views/users/_user.html.erb
<%= form_for @user, url: '/users' do |f| %>
Username: <%= f.text_field :name %>
email: <%= f.text_field :email %>
Password: <%= f.password_field :password %>
Password Confirmation: <%= f.password_field :password_confirmation %>
<%= f.submit "Submit" %>
<% end %>

app/views/users/new.html.erb
<%= render 'form' %>

app/views/users/show.html.erb
<ul>
  <li>User: <%= @user.name %> <%= link_to 'edit', edit_user_path(@user) %></li>
  <li>email: <%= @user.email %></li>
  <li>ID: <%= @user.id %></li>
</ul>

app/views/users/welcome.html.erb
<h3>Welcome to Streaming Watchlist</h3>

<% if logged_in? %>

<% if @user.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

  <h3> Your Watchlists </h3>
  <div id="wLists">
    <% if @watchlists %>
      <%= render @watchlists %>
    <% end %>
</div>
  <p><%= link_to 'Create New Watchlist', new_watchlist_path %></p>
  <p><%= link_to 'Add New Show', new_show_path %></p>
  <p id="search"><%= link_to 'Search', shows_search_path %></p>

<% end %>