config/routes.rb
Rails.application.routes.draw do
  get '/auth/amazon/callback' => 'sessions#create'
  get 'shows/search' => 'shows#search'
  post 'shows/result' => 'shows#results'
  resources :shows do
    resources :comments
  end
  resources :watchlists
  resources :users, only: [:show, :new, :create, :edit, :update]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'users#welcome'
  get 'users/welcome' => 'users#welcome'
  get 'sessions/sign_in' => 'sessions#new'
  post 'sessions/create' => 'sessions#create'
  get "sessions/destroy" => 'sessions#destroy'


end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>StreamingWatchlist</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

<body>
  <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <a class="navbar-brand" href="<%= root_path %>"/>Home</a>
      <div class=navlinks>
        <% if logged_in? %>
          <p><%= link_to current_user.name, user_path(current_user.id) %>" "<%= link_to "Log Out", sessions_destroy_path %></p>
        <% else %>
          <p><%= link_to "Sign Up", new_user_path %>" "
          <%= link_to "Sign In", sessions_sign_in_path %>" "
          <%= link_to "Sign in with Amazon", '/auth/amazon' %></p>
        <% end %>
      </div>
  </div>
      <div class="flex-container">
        <div class="background">
          <div class="content">
            <% flash.each do |name, msg| -%>
            <%= content_tag :div, msg, class: name %>
            <% end -%>
            <%= yield %>
          </div>
        </div>
      </div>

  </body>
</html>